language: node_js
node_js:
  - "14"
  - "12"
  - "10"
  - "8"
os:
  - linux
  - osx
  - windows
sudo: false
install:
  - npm --version
  - npm install
script:
  - npm test
after_success:
  - npm run coverage
